name: schafkopfer_api
version: 1.0.1
author: Florian Hirsch
description: Api for the Schafkopfer
homepage: utkast.de/schafkopfer
dependencies:
  bson: any
  intl: any
  route: any
dev_dependencies:
  unittest: any
