name: schafkopfer_server
version: 1.0.0
author: Florian Hirsch
description: RESTful server for schafkopfer
homepage: utkast.de/schafkopfer
dependencies:
  connection_pool: any
  http_server: any
  intl: any
  logging: any
  logging_handlers: any
  mongo_dart: any
  route: any
  schafkopfer_api:
    path: ../schafkopfer_api
  yaml: any
dev_dependencies:
  unittest: any
